version: '3.8'

services:
  db:
    image: docker.io/postgres:17-alpine
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-logback}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-logback}
    ports:
      - "5432:5432"
    networks:
      - logback

  app:
    build: .
    env_file: ".env"
    environment:
      LOGBACK_SERVER_PORT: 80
      LOGBACK_DB_HOST: db
      LOGBACK_DB_PORT: 5432
      LOGBACK_DB_USER: ${POSTGRES_USER:-logback}
      LOGBACK_DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
      LOGBACK_DB_NAME: ${POSTGRES_DB:-logback}
    ports:
      - "3000:80"
    depends_on:
      - db
    networks:
      - logback

networks:
  logback:
    driver: bridge
